# Generated by Django 3.0.2 on 2020-01-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('venues', models.ManyToManyField(to='venues.Venue')),
            ],
        ),
    ]
