# Generated by Django 3.0.2 on 2020-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuelist',
            name='venues',
            field=models.ManyToManyField(related_name='lists', to='venues.Venue'),
        ),
    ]
