# Generated by Django 3.0.2 on 2020-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20200116_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
